### ISSUE TITLE
Inconsistency between Generated Signature and BIP-0322 Standard

### ISSUE THREAD

**Issue by bubbly-hb** [ACken2/bip322#4]
**Description:**
I have encountered an issue with the generated signature using the **_Signer.sign_**. The signature produced by the implementation does not align with the expected format outlined in the [BIP-0322 standard](https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki).

**Steps to Reproduce:**
Use the provided BIP-0322 implementation to generate a signature. Given below parameters:
private key = **L3VFeEujGtevx9w18HD1fhRbCH67Az2dpCymeRE1SoPK6XQtaN2k**
corresponding address = **bc1q9vza2e8x573nczrlzms0wvx3gsqjx7vavgkx0l**
Message = **"Hello World"**

**Expected Signatures:**
AkcwRAIgZRfIY3p7/DoVTty6YZbWS71bc5Vct9p9Fia83eRmw2QCICK/ENGfwLtptFluMGs2KsqoNSk89pO7F29zJLUx9a/sASECx/EgAxlkQpQ9hYjgGu6EBCPMVPwVIVJqO4XCsMvViHI=

**Actual Signatures:**
AkgwRQIhAOzyynlqt93lOKJr+wmmxIens//zPzl9tqIOua93wO6MAiBi5n5EyAcPScOjf1lAqIUIQtr3zKNeavYabHyR8eGhowEhAsfxIAMZZEKUPYWI4BruhAQjzFT8FSFSajuFwrDL1Yhy

When using **_Verifier.verifySignature_**, both of the above signatures are **valid**.

**Comment by ACken2** [comment]
I believe both signature are valid as the same signature can be reproduced in another implementation based on [buidl-python](https://github.com/buidl-bitcoin/buidl-python) library, which can be found [here](https://github.com/LegReq/bip0322-signatures/blob/master/BIP0322_signing.ipynb).

The same signature was also included in a test script [here](https://github.com/bitcoin/bitcoin/commit/63a2f592c38a40ebe720eb547ade5aa9b06ade6d).

I am not sure why there exists multiple valid BIP-322 signature for the same message though.
